### ISSUE TITLE
Titanium.Web.Proxy repository failed to add

### ISSUE THREAD

**Issue by shushu789** [upstash/context7#112]
Titanium.Web.Proxy repository failed to add, please fix

**Comment by Afaqahmad1122** [comment]
Check other issues and you'll find the solution.

**Comment by enesakar** [comment]
can you share the repo url please?

**Comment by shushu789** [comment]
@enesakar This is the repository URL: https://github.com/justcoding121/titanium-web-proxy, according to the error message added, it mentions:
Parsing completed
Error processing new repository
No snippets found in the repo

But in fact, the repository document has a lot of code examples, and I also forked to my repository, and when I added it again, it was still the same error。

<img width="916" alt="Image" src="https://github.com/user-attachments/assets/4481f68f-4c7a-4187-be35-054b6ff66f45" />

**Comment by Afaqahmad1122** [comment]
go to issue no #19

**Comment by enesakar** [comment]
I fixed the issue, will start parsing your repo now.

**Comment by shushu789** [comment]
@Afaqahmad1122 Oh, sorry, I didn't explain it clearly. My problem was not with the call to the mcp server. I was referring to the failure to add the above repository on the "https://context7.com/add-library" page.
So this question should have nothing to do with #19 。
hi @enesakar ，The page still shows an error, and it doesn't seem to be fixed.

<img width="806" alt="Image" src="https://github.com/user-attachments/assets/4a9e17cd-7dd0-4fb7-9e33-d8ca3dd1f3f3" />

<img width="956" alt="Image" src="https://github.com/user-attachments/assets/dd2995db-96b8-40b1-83d8-363fa37ef210" />

**Comment by enesakar** [comment]
https://context7.com/justcoding121/titanium-web-proxy

can you try now?

**Comment by shushu789** [comment]
@enesakar Great, it's fixed.
However, when I searched the list page, I saw that its status was still in error state, but the details page was in normal state, so the status was not synchronized successfully. There is another forked repository (https://github.com/hanosteam/titanium-web-proxy), can it be moved out? Because it is still in error state, I just tried to refresh it, and it didn't work. To avoid confusion, you can remove it and only keep the original one: https://github.com/justcoding121/titanium-web-proxy. Or you can fix it.
Thank you very much.

<img width="977" alt="Image" src="https://github.com/user-attachments/assets/4a115950-b747-4f19-8125-b4db3a72921a" />

<img width="919" alt="Image" src="https://github.com/user-attachments/assets/a7089f1b-a9d3-4bfd-9aad-f515eb246952" />

**Comment by enesakar** [comment]
i see. i removed /hanosteam/titanium-web-proxy

![Image](https://github.com/user-attachments/assets/e58a032b-74e0-436c-b345-729a4dead7ad)
